spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/bookstore
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 자동으로 테이블을 만들어줌
    properties:
      hibernate:
        #show_sql: true   # 이넘은 시스템 아웃에 출력하는 거고 logging.level.org.hibernate는  로거를 통해 표현됩니다.
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # 하이버네이트가 생성하는 sql이 다 보인다.